---
- name: Uninstall nginx server
  hosts: practice
  tasks:
  - name: stop nginx
    service:
      name: nginx
      state: stopped
  - name: unintall nginx
    yum:
      name: nginx
      state: absent